### ISSUE TITLE
spam repository

### ISSUE THREAD

**Issue by ghost** [hololive233/HoloLiveMomentsJP#3]
please use a [gist](https://gist.github.com) or a [pastebin](https://pastebin.com) next you try to put up a wall of text, it's a more proper place to do so

**Comment by Daidaiowo** [comment]
嗨

**Comment by 424778940z** [comment]
> please use a [gist](https://gist.github.com) or a [pastebin](https://pastebin.com) next you try to put up a wall of text, it's a more proper place to do so

lol they are the repo owner not you, and Github welcom all kinds of stuff, who give you the privilege to tell people what to do with their own repo.
